insert into entitlement (id, org_id, asset_id, kind, slot, days)
select uuid_generate_v5('3b1f7d5e-9c2a-4e6b-8f0d-1a2b3c4d5e6f'::uuid, 'entitlement:' || o.id || '|' || a.id || '|' || v.kind || '|' || coalesce(v.slot, '')), o.id, a.id, v.kind::entitlement_kind, v.slot::slot, v.days
from (values
('Riverside University Crew', 'The Ashford', 'eligible', NULL, NULL::int[]),
('Riverside University Crew', 'The Halden', 'eligible', NULL, NULL::int[]),
('Riverside University Crew', 'The Brackett', 'eligible', NULL, NULL::int[]),
('Riverside University Crew', 'The Marlowe', 'eligible', NULL, NULL::int[]),
('Riverside University Crew', 'The Pemberton', 'eligible', NULL, NULL::int[]),
('Riverside University Crew', 'The Whitcombe', 'eligible', NULL, NULL::int[]),
('Riverside University Crew', 'The Falcon', 'eligible', NULL, NULL::int[]),
('Riverside University Crew', 'The Heron', 'eligible', NULL, NULL::int[]),
('Riverside University Crew', 'The Osprey', 'eligible', NULL, NULL::int[]),
('Riverside University Crew', 'Club Fifteen', 'eligible', NULL, NULL::int[]),
('Riverside University Crew', 'The Ashford', 'standing', 'AM1', '{1,2,3,4,5}'::int[]),
('Harbor Rowing Club', 'The Ashford', 'eligible', NULL, NULL::int[]),
('Harbor Rowing Club', 'The Halden', 'eligible', NULL, NULL::int[]),
('Harbor Rowing Club', 'The Brackett', 'eligible', NULL, NULL::int[]),
('Harbor Rowing Club', 'The Lockwood', 'eligible', NULL, NULL::int[]),
('Harbor Rowing Club', 'The Marlowe', 'eligible', NULL, NULL::int[]),
('Harbor Rowing Club', 'The Pemberton', 'eligible', NULL, NULL::int[]),
('Harbor Rowing Club', 'The Kestrel', 'eligible', NULL, NULL::int[]),
('Harbor Rowing Club', 'The Whitcombe', 'eligible', NULL, NULL::int[]),
('Harbor Rowing Club', 'The Sandpiper', 'eligible', NULL, NULL::int[]),
('Harbor Rowing Club', 'The Driftwood', 'eligible', NULL, NULL::int[]),
('Harbor Rowing Club', 'The Falcon', 'eligible', NULL, NULL::int[]),
('Harbor Rowing Club', 'The Heron', 'eligible', NULL, NULL::int[]),
('Harbor Rowing Club', 'The Osprey', 'eligible', NULL, NULL::int[]),
('Harbor Rowing Club', 'The Minnow', 'eligible', NULL, NULL::int[]),
('Harbor Rowing Club', 'The Halden', 'standing', 'AM2', '{1,3,5}'::int[]),
('Eastside Community Rowing', 'The Ashford', 'eligible', NULL, NULL::int[]),
('Eastside Community Rowing', 'The Halden', 'eligible', NULL, NULL::int[]),
('Eastside Community Rowing', 'The Brackett', 'eligible', NULL, NULL::int[]),
('Eastside Community Rowing', 'The Lockwood', 'eligible', NULL, NULL::int[]),
('Eastside Community Rowing', 'The Marlowe', 'eligible', NULL, NULL::int[]),
('Eastside Community Rowing', 'The Pemberton', 'eligible', NULL, NULL::int[]),
('Eastside Community Rowing', 'The Kestrel', 'eligible', NULL, NULL::int[]),
('Eastside Community Rowing', 'The Whitcombe', 'eligible', NULL, NULL::int[]),
('Eastside Community Rowing', 'The Sandpiper', 'eligible', NULL, NULL::int[]),
('Eastside Community Rowing', 'The Driftwood', 'eligible', NULL, NULL::int[]),
('Eastside Community Rowing', 'The Heron', 'eligible', NULL, NULL::int[]),
('Eastside Community Rowing', 'The Osprey', 'eligible', NULL, NULL::int[]),
('Eastside Community Rowing', 'The Minnow', 'eligible', NULL, NULL::int[]),
('Harbor Rowing Club', 'Sweep Set A', 'eligible', NULL, NULL::int[]),
('Harbor Rowing Club', 'Sweep Set B', 'eligible', NULL, NULL::int[]),
('Harbor Rowing Club', 'Sweep Set C', 'eligible', NULL, NULL::int[]),
('Harbor Rowing Club', 'Sweep Set D', 'eligible', NULL, NULL::int[]),
('Harbor Rowing Club', 'Scull Set A', 'eligible', NULL, NULL::int[]),
('Harbor Rowing Club', 'Scull Set B', 'eligible', NULL, NULL::int[]),
('Riverside University Crew', 'Sweep Set A', 'eligible', NULL, NULL::int[]),
('Riverside University Crew', 'Sweep Set B', 'eligible', NULL, NULL::int[]),
('Riverside University Crew', 'Sweep Set C', 'eligible', NULL, NULL::int[]),
('Riverside University Crew', 'Sweep Set D', 'eligible', NULL, NULL::int[]),
('Riverside University Crew', 'Scull Set A', 'eligible', NULL, NULL::int[]),
('Riverside University Crew', 'Scull Set B', 'eligible', NULL, NULL::int[]),
('Eastside Community Rowing', 'Sweep Set A', 'eligible', NULL, NULL::int[]),
('Eastside Community Rowing', 'Sweep Set B', 'eligible', NULL, NULL::int[]),
('Eastside Community Rowing', 'Sweep Set C', 'eligible', NULL, NULL::int[]),
('Eastside Community Rowing', 'Sweep Set D', 'eligible', NULL, NULL::int[]),
('Eastside Community Rowing', 'Scull Set A', 'eligible', NULL, NULL::int[]),
('Eastside Community Rowing', 'Scull Set B', 'eligible', NULL, NULL::int[])
) as v(org_name, asset_name, kind, slot, days)
join organization o on o.name = v.org_name
join asset a on a.name = v.asset_name;
